apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spring-kubernetes-roledbiding
  namespace: study
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spring-kubernetes-role
subjects:
- kind: ServiceAccount
  name: spring-kubernetes
  namespace: study