apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: study
  name: spring-kubernetes-role
rules:
- apiGroups: [""]
  resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
  verbs: ["get", "watch", "list"]