apiVersion: v1
kind: Service
metadata:
  name: spring-kubernetes-service
  namespace: study
  labels:
    app: spring-kubernetes
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: spring-kubernetes
